"use strict";

const fs = require("fs-extra");
const path = require("path");
const { runSilent } = require("../../core/runCommand");

async function generate({ name, template, targetDir, onStep }) {
  const parentDir = path.dirname(targetDir);
  const useMaterial = template === "material";
  const useTailwind = template === "tailwind";

  // -----------------------------
  // 1. Create Angular Project
  // -----------------------------
  onStep("Scaffolding Angular project");

  await runSilent(
    `npx @angular/cli@latest new "${name}" --routing --style=scss --skip-git --skip-install`,
    { cwd: parentDir }
  );

  // -----------------------------
  // 2. Install dependencies
  // -----------------------------
  onStep("Installing dependencies");

  await runSilent("npm install", { cwd: targetDir });

  // -----------------------------
  // 3. Angular Material
  // -----------------------------
  if (useMaterial) {
    onStep("Adding Angular Material");

    await runSilent("npx ng add @angular/material --skip-confirmation", {
      cwd: targetDir,
      shell: true,
    });
  }

  // -----------------------------
  // 4. Tailwind Setup
  // -----------------------------
  if (useTailwind) {
    onStep("Adding Tailwind CSS");

    await runSilent("npm install -D tailwindcss @tailwindcss/postcss postcss", {
      cwd: targetDir,
    });

    // postcss.config.mjs — tells Angular's build pipeline to use
    // @tailwindcss/postcss instead of the old tailwindcss PostCSS plugin.
    // Tailwind v4 split the PostCSS integration into its own package;
    // without this file Angular's esbuild stylesheet pipeline throws the error
    // "trying to use tailwindcss directly as a PostCSS plugin".
    fs.writeFileSync(
      path.join(targetDir, "postcss.config.mjs"),
      `export default {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
`
    );

    // Remove the CJS variant if the Angular CLI wrote one, so there is only
    // one PostCSS config and no loader-ambiguity between CJS and ESM.
    const cjsPostcss = path.join(targetDir, "postcss.config.js");
    if (fs.existsSync(cjsPostcss)) {
      fs.removeSync(cjsPostcss);
    }

    // Tailwind v4 no longer needs a tailwind.config.js — the single CSS
    // @import is the entrypoint for the entire framework.
    fs.appendFileSync(
      path.join(targetDir, "src", "styles.scss"),
      `\n@import "tailwindcss";\n`
    );
  }

  // -----------------------------
  // 5. Git Init
  // -----------------------------
  onStep("Initializing Git");

  try {
    await runSilent("git init", { cwd: targetDir });
  } catch {}

  // -----------------------------
  // 6. README
  // -----------------------------
  onStep("Writing README");

  const readme = `# ${name}

Generated by **PIC-LI**

## Stack
- Angular${useMaterial ? "\n- Angular Material" : ""}${
    useTailwind ? "\n- Tailwind CSS v4" : ""
  }

## Run

\`\`\`bash
ng serve
\`\`\`

Open http://localhost:4200
`;

  await fs.writeFile(path.join(targetDir, "README.md"), readme);
}

module.exports = { generate };
