"use strict";

const fs = require("fs-extra");
const path = require("path");
const { runSilent } = require("../../core/runCommand");

async function generate({ name, template, targetDir, onStep }) {
  const useTailwind = template.includes("tailwind");
  const useTs = template.includes("typescript");
  const parentDir = path.dirname(targetDir);

  // -----------------------------
  // 1. Scaffold Next.js Project
  // -----------------------------
  onStep("Scaffolding with create-next-app");

  const flags = [
    "--yes",
    "--app",
    "--eslint",
    "--no-git",
    "--no-import-alias",
    useTailwind ? "--tailwind" : "--no-tailwind",
    useTs ? "--typescript" : "--js",
    "--src-dir",
  ].join(" ");

  await runSilent(`npx create-next-app@latest "${name}" ${flags}`, {
    cwd: parentDir,
  });

  // -----------------------------
  // 2. Ensure Project Ready
  // -----------------------------
  if (!(await fs.pathExists(targetDir))) {
    throw new Error("Project creation failed: target directory not found");
  }

  // -----------------------------
  // 3. Create Extra Structure
  // -----------------------------
  onStep("Creating extra folders");

  await fs.ensureDir(path.join(targetDir, "src", "components"));
  await fs.ensureDir(path.join(targetDir, "src", "lib"));

  // -----------------------------
  // 4. Initialize Git
  // -----------------------------
  onStep("Initializing Git");

  try {
    await runSilent("git init", { cwd: targetDir });
  } catch (err) {
    // ignore git errors
  }

  // -----------------------------
  // 5. Clean .next if exists (safety)
  // -----------------------------
  const nextBuildDir = path.join(targetDir, ".next");
  if (await fs.pathExists(nextBuildDir)) {
    await fs.remove(nextBuildDir);
  }

  // -----------------------------
  // 6. Write README
  // -----------------------------
  onStep("Writing README");

  const readme = `# ${name}

Generated by **PIC-LI** 🚀

## Stack
- Next.js (App Router)
${useTs ? "- TypeScript" : "- JavaScript"}
${useTailwind ? "- Tailwind CSS v4" : ""}

## Getting Started

\`\`\`bash
npm run dev
\`\`\`

Open http://localhost:3000

## Project Structure

\`\`\`
src/
  app/
  components/
  lib/
\`\`\`

## Notes
- Uses modern Next.js App Router
- Tailwind v4 (if enabled)
`;

  await fs.writeFile(path.join(targetDir, "README.md"), readme);
}

module.exports = { generate };
