"use strict";

const fs = require("fs-extra");
const path = require("path");
const { runSilent } = require("../../core/runCommand");

async function generate({ name, template, targetDir, onStep }) {
  const useTs = template.includes("typescript");
  const useTailwind = template.includes("tailwind");
  const parentDir = path.dirname(targetDir);

  // -----------------------------
  // 1. Scaffold Vue Project
  // -----------------------------
  onStep("Scaffolding Vue 3 + Vite");

  await runSilent(
    `npx create-vite@latest "${name}" --template ${useTs ? "vue-ts" : "vue"}`,
    { cwd: parentDir }
  );

  // -----------------------------
  // 2. Install Dependencies
  // -----------------------------
  onStep("Installing dependencies");

  await runSilent("npm install", { cwd: targetDir });

  // -----------------------------
  // 3. Tailwind Setup
  // -----------------------------
  // -----------------------------
  // 3. Tailwind Setup
  // -----------------------------
  if (useTailwind) {
    onStep("Adding Tailwind CSS");

    // Tailwind v4 packages
    await runSilent(
      "npm install -D tailwindcss @tailwindcss/postcss postcss autoprefixer",
      { cwd: targetDir }
    );

    // Tailwind config
    fs.writeFileSync(
      path.join(targetDir, "tailwind.config.js"),
      `export default {
  content: ['./index.html','./src/**/*.{vue,js,ts}'],
  theme: {
    extend: {},
  },
  plugins: [],
}
`
    );

    // Updated PostCSS config for Tailwind v4
    fs.writeFileSync(
      path.join(targetDir, "postcss.config.js"),
      `export default {
  plugins: {
    '@tailwindcss/postcss': {},
    autoprefixer: {},
  },
}
`
    );

    // Main CSS
    fs.writeFileSync(
      path.join(targetDir, "src", "style.css"),
      `@tailwind base;
@tailwind components;
@tailwind utilities;
`
    );
  }

  // -----------------------------
  // 4. Extra Structure
  // -----------------------------
  onStep("Creating folder structure");

  await fs.ensureDir(path.join(targetDir, "src", "components"));
  await fs.ensureDir(path.join(targetDir, "src", "composables"));

  // -----------------------------
  // 5. Git Init
  // -----------------------------
  onStep("Initializing Git");

  try {
    await runSilent("git init", { cwd: targetDir });
  } catch {}

  // -----------------------------
  // 6. README
  // -----------------------------
  onStep("Writing README");

  const readme = `# ${name}

Generated by **PIC-LI** 🚀

## Stack
- Vue 3 + Vite
${useTs ? "- TypeScript" : "- JavaScript"}
${useTailwind ? "- Tailwind CSS" : ""}

## Getting Started

\`\`\`bash
npm run dev
\`\`\`
`;

  await fs.writeFile(path.join(targetDir, "README.md"), readme);
}

module.exports = { generate };
