"use strict";

const STACKS = {
  // ── React ──────────────────────────────────────────────────────────────────
  "react-vite": {
    label: "React + Vite",
    category: "Frontend",
    description: "Fast dev server, HMR, modern bundler",
    requires: ["node", "npm"],
    templates: ["default", "tailwind", "tailwind-shadcn", "typescript"],
    templateAliases: {
      ts: "typescript",
      "react ts": "typescript",
      "react typescript": "typescript",
      "with-typescript": "typescript",
      "with typescript": "typescript",
      "tailwind css": "tailwind",
      tailwindcss: "tailwind",
      shadcn: "tailwind-shadcn",
      "tailwind shadcn": "tailwind-shadcn",
      "shadcn/ui": "tailwind-shadcn",
      "tailwind + shadcn": "tailwind-shadcn",
    },
    generator: "react/vite",
    runCmd: "npm run dev",
    buildCmd: "npm run build",
    devPort: 5173,
  },

  "react-cra": {
    label: "React (Create React App)",
    category: "Frontend",
    description: "Classic zero-config React setup",
    requires: ["node", "npm"],
    templates: ["default", "typescript"],
    templateAliases: {
      ts: "typescript",
      "react ts": "typescript",
      "react typescript": "typescript",
      "with-typescript": "typescript",
      "with typescript": "typescript",
    },
    generator: "react/cra",
    runCmd: "npm start",
    buildCmd: "npm run build",
    devPort: 3000,
  },

  nextjs: {
    label: "Next.js",
    category: "Frontend",
    description: "SSR, SSG, App Router, API routes",
    requires: ["node", "npm"],
    templates: ["default", "tailwind", "typescript", "tailwind-typescript"],
    templateAliases: {
      ts: "typescript",
      "next ts": "typescript",
      "next typescript": "typescript",
      "with-typescript": "typescript",
      "tailwind css": "tailwind",
      tailwindcss: "tailwind",
      "tailwind + typescript": "tailwind-typescript",
      "tailwind ts": "tailwind-typescript",
      "typescript + tailwind": "tailwind-typescript",
    },
    generator: "frontend/nextjs",
    runCmd: "npm run dev",
    buildCmd: "npm run build",
    devPort: 3000,
  },

  vue: {
    label: "Vue 3 + Vite",
    category: "Frontend",
    description: "Composition API, fast bundler",
    requires: ["node", "npm"],
    templates: ["default", "typescript", "tailwind"],
    templateAliases: {
      ts: "typescript",
      "vue ts": "typescript",
      "vue typescript": "typescript",
      "with-typescript": "typescript",
      "tailwind css": "tailwind",
      tailwindcss: "tailwind",
    },
    generator: "frontend/vue",
    runCmd: "npm run dev",
    buildCmd: "npm run build",
    devPort: 5173,
  },

  angular: {
    label: "Angular",
    category: "Frontend",
    description: "Full framework with TypeScript",
    requires: ["node", "npm"],
    templates: ["default", "material", "tailwind"],
    templateAliases: {
      "angular material": "material",
      "tailwind css": "tailwind",
      tailwindcss: "tailwind",
      "angular tailwind": "tailwind",
    },
    generator: "frontend/angular",
    runCmd: "npm start",
    buildCmd: "ng build",
    devPort: 4200,
  },

  // ── Backend (Node) ─────────────────────────────────────────────────────────
  express: {
    label: "Express.js",
    category: "Backend (Node)",
    description: "Minimal Node.js web framework",
    requires: ["node", "npm"],
    templates: ["default", "crud", "mongo", "postgres"],
    templateAliases: {
      rest: "crud",
      "rest-crud": "crud",
      "rest crud": "crud",
      "rest api": "crud",
      "rest-api": "crud",
      "rest api (crud)": "crud",
      "in-memory crud": "crud",
      "crud rest": "crud",
      mongodb: "mongo",
      mongoose: "mongo",
      "mongodb (mongoose)": "mongo",
      "rest-api-mongo": "mongo",
      "rest api mongo": "mongo",
      "express + mongodb": "mongo",
      "express + mongodb (mongoose)": "mongo",
      postgresql: "postgres",
      sequelize: "postgres",
      "postgresql (sequelize)": "postgres",
      "rest-api-postgres": "postgres",
      "rest api postgres": "postgres",
      "express + postgresql": "postgres",
      "express + postgresql (sequelize)": "postgres",
    },
    generator: "backend/express",
    runCmd: "npm run dev",
    buildCmd: null,
    devPort: 3000,
  },

  nestjs: {
    label: "NestJS",
    category: "Backend (Node)",
    description: "Progressive TypeScript-first Node framework",
    requires: ["node", "npm"],
    templates: ["default", "crud", "graphql", "microservice"],
    templateAliases: {
      rest: "crud",
      "rest-api": "crud",
      "rest api": "crud",
      "crud-rest": "crud",
      "nestjs crud": "crud",
      "nestjs rest": "crud",
      "graphql api": "graphql",
      "nestjs graphql": "graphql",
      micro: "microservice",
      microservices: "microservice",
      "microservice (tcp)": "microservice",
      "nestjs microservice": "microservice",
    },
    generator: "backend/nestjs",
    runCmd: "npm run start:dev",
    buildCmd: "npm run build",
    devPort: 3000,
  },

  // ── Backend (Java) ─────────────────────────────────────────────────────────
  "spring-boot": {
    label: "Spring Boot",
    category: "Backend (Java)",
    description: "Java REST/MVC — Maven build",
    requires: ["java", "mvn"],
    // Canonical template IDs — must match what the generator checks after normalization.
    // The generator normalizes "rest-api-mysql" → "mysql" and "rest-api-postgres" → "postgres"
    // so those long-form aliases resolve correctly too.
    templates: ["default", "rest-api", "mysql", "postgres", "microservice"],
    templateAliases: {
      // rest-api (H2)
      rest: "rest-api",
      crud: "rest-api",
      "spring rest": "rest-api",
      "rest api": "rest-api",
      h2: "rest-api",
      // mysql
      "rest-api-mysql": "mysql", // long-form → canonical
      "spring mysql": "mysql",
      "jpa mysql": "mysql",
      // postgres
      postgresql: "postgres",
      "rest-api-postgres": "postgres", // long-form → canonical
      "spring postgres": "postgres",
      "jpa postgres": "postgres",
      // microservice
      micro: "microservice",
      microservices: "microservice",
    },
    generator: "backend/spring-boot",
    runCmd: "mvn spring-boot:run",
    buildCmd: "mvn package",
    devPort: 8080,
    buildTool: "maven",
  },

  "spring-gradle": {
    label: "Spring Boot + Gradle",
    category: "Backend (Java)",
    description: "Java REST/MVC — Gradle build",
    requires: ["java", "gradle"],
    templates: ["default", "rest-api", "mysql"],
    templateAliases: {
      rest: "rest-api",
      crud: "rest-api",
      "spring rest": "rest-api",
      "rest-api-mysql": "mysql",
      "spring mysql": "mysql",
    },
    generator: "backend/spring-boot",
    runCmd: "gradlew bootRun",
    buildCmd: "gradlew build",
    devPort: 8080,
    buildTool: "gradle",
  },

  // ── Backend (Python) ───────────────────────────────────────────────────────
  fastapi: {
    label: "FastAPI",
    category: "Backend (Python)",
    description: "Async Python API with auto OpenAPI docs",
    requires: ["python", "pip"],
    templates: ["default", "with-sqlalchemy", "with-mongodb", "full-stack"],
    templateAliases: {
      basic: "default",
      minimal: "default",
      "fastapi basic": "default",
      sqlalchemy: "with-sqlalchemy",
      "fastapi sqlalchemy": "with-sqlalchemy",
      "with sqlalchemy": "with-sqlalchemy",
      mongodb: "with-mongodb",
      mongo: "with-mongodb",
      "fastapi mongo": "with-mongodb",
      "with mongo": "with-mongodb",
      "full stack": "full-stack",
      fullstack: "full-stack",
    },
    generator: "backend/fastapi",
    runCmd: "uvicorn app.main:app --reload",
    buildCmd: null,
    devPort: 8000,
    activate: true,
  },

  flask: {
    label: "Flask",
    category: "Backend (Python)",
    description: "Lightweight Python micro-framework",
    requires: ["python", "pip"],
    templates: ["default", "rest-api", "with-sqlalchemy"],
    templateAliases: {
      basic: "default",
      "flask basic": "default",
      "flask default": "default",
      rest: "rest-api",
      crud: "rest-api",
      "flask rest": "rest-api",
      "flask rest api": "rest-api",
      "flask-restful": "rest-api",
      sqlalchemy: "with-sqlalchemy",
      "flask sqlalchemy": "with-sqlalchemy",
      "flask + sqlalchemy": "with-sqlalchemy",
      "with sqlalchemy": "with-sqlalchemy",
    },
    generator: "backend/flask",
    runCmd: "flask run",
    buildCmd: null,
    devPort: 5000,
    activate: true,
  },

  django: {
    label: "Django",
    category: "Backend (Python)",
    description: "Batteries-included Python web framework",
    requires: ["python", "pip"],
    templates: ["default", "with-drf", "with-postgres"],
    templateAliases: {
      basic: "default",
      "django basic": "default",
      "django default": "default",
      drf: "with-drf",
      "rest framework": "with-drf",
      "django rest": "with-drf",
      "rest-framework": "with-drf",
      "django rest framework": "with-drf",
      "django + drf": "with-drf",
      postgres: "with-postgres",
      postgresql: "with-postgres",
      "django postgres": "with-postgres",
      "django + postgres": "with-postgres",
    },
    generator: "backend/django",
    runCmd: "python manage.py runserver",
    buildCmd: null,
    devPort: 8000,
    activate: true,
  },

  // ── Mobile ─────────────────────────────────────────────────────────────────
  flutter: {
    label: "Flutter",
    category: "Mobile",
    description: "Cross-platform iOS, Android, Web, Desktop",
    requires: ["flutter", "dart"],
    templates: ["default", "with-provider", "with-riverpod", "with-bloc"],
    templateAliases: {
      provider: "with-provider",
      "flutter provider": "with-provider",
      riverpod: "with-riverpod",
      "flutter riverpod": "with-riverpod",
      bloc: "with-bloc",
      "flutter bloc": "with-bloc",
      "flutter + bloc": "with-bloc",
    },
    generator: "mobile/flutter",
    runCmd: "flutter run",
    buildCmd: "flutter build apk",
    devPort: null,
  },

  "react-native": {
    label: "React Native (Expo)",
    category: "Mobile",
    description: "Cross-platform iOS & Android with Expo",
    requires: ["node", "npm"],
    templates: ["default", "tabs", "with-typescript"],
    templateAliases: {
      "tab navigation": "tabs",
      "tab-navigation": "tabs",
      "bottom tabs": "tabs",
      ts: "with-typescript",
      typescript: "with-typescript",
      "with typescript": "with-typescript",
      "expo typescript": "with-typescript",
    },
    generator: "react/native",
    runCmd: "npx expo start",
    buildCmd: "npx expo build",
    devPort: null,
  },

  // ── Fullstack ──────────────────────────────────────────────────────────────
  mern: {
    label: "MERN Stack",
    category: "Fullstack",
    description: "MongoDB + Express + React + Node monorepo",
    requires: ["node", "npm"],
    templates: ["default", "with-auth", "with-tailwind"],
    templateAliases: {
      "mern default": "default",
      "mern basic": "default",
      auth: "with-auth",
      jwt: "with-auth",
      "mern auth": "with-auth",
      "mern with auth": "with-auth",
      tailwind: "with-tailwind",
      tailwindcss: "with-tailwind",
      "mern tailwind": "with-tailwind",
    },
    generator: "fullstack/mern",
    runCmd: "npm run dev",
    buildCmd: "npm run build",
    devPort: 3000,
    installCmd: "npm run install:all",
  },

  // ── Go ─────────────────────────────────────────────────────────────────────
  go: {
    label: "Go + Gin",
    category: "Backend (Go)",
    description: "Fast Go REST API with Gin framework",
    requires: ["go"],
    templates: ["default", "rest-crud", "with-gorm"],
    templateAliases: {
      rest: "rest-crud",
      crud: "rest-crud",
      "rest-api": "rest-crud",
      "go rest": "rest-crud",
      "go crud": "rest-crud",
      "gin crud": "rest-crud",
      "gin rest": "rest-crud",
      gorm: "with-gorm",
      "go gorm": "with-gorm",
      "gin gorm": "with-gorm",
      "gin + gorm": "with-gorm",
    },
    generator: "misc/go",
    runCmd: "go run ./cmd/server",
    buildCmd: "go build -o bin/server ./cmd/server",
    devPort: 8080,
  },
};

const CATEGORIES = [
  "Frontend",
  "Backend (Node)",
  "Backend (Java)",
  "Backend (Python)",
  "Mobile",
  "Fullstack",
  "Backend (Go)",
];

const ADD_INTEGRATIONS = {
  tailwind: {
    label: "Tailwind CSS",
    supports: ["react-vite", "react-cra", "nextjs", "vue", "mern"],
  },
  firebase: {
    label: "Firebase",
    supports: [
      "react-vite",
      "react-cra",
      "nextjs",
      "vue",
      "react-native",
      "flutter",
    ],
  },
  eslint: {
    label: "ESLint + Prettier",
    supports: [
      "react-vite",
      "react-cra",
      "nextjs",
      "vue",
      "express",
      "nestjs",
      "mern",
    ],
  },
  docker: {
    label: "Docker",
    supports: [
      "express",
      "nestjs",
      "fastapi",
      "flask",
      "django",
      "spring-boot",
      "go",
    ],
  },
  prisma: { label: "Prisma ORM", supports: ["express", "nestjs"] },
  mongoose: { label: "Mongoose", supports: ["express", "nestjs", "mern"] },
  shadcn: { label: "shadcn/ui", supports: ["react-vite", "nextjs"] },
  husky: {
    label: "Husky + lint-staged",
    supports: [
      "react-vite",
      "react-cra",
      "nextjs",
      "vue",
      "express",
      "nestjs",
      "mern",
    ],
  },
  auth: {
    label: "JWT Auth",
    supports: ["express", "nestjs", "fastapi", "flask", "django"],
  },
};

module.exports = { STACKS, CATEGORIES, ADD_INTEGRATIONS };
