'use strict';
const fs = require('fs-extra');
const path = require('path');
const { runSilent } = require('../../core/runCommand');

async function generate({ name, template, targetDir, onStep }) {
  const useTs = template.includes('typescript');
  const parentDir = path.dirname(targetDir);
  onStep('Scaffolding with Create React App');
  runSilent(`npx --yes create-react-app "${name}" ${useTs ? '--template typescript' : ''}`, { cwd: parentDir });
  onStep('Creating folder structure');
  fs.ensureDirSync(path.join(targetDir, 'src', 'components'));
  fs.ensureDirSync(path.join(targetDir, 'src', 'pages'));
  fs.ensureDirSync(path.join(targetDir, 'src', 'hooks'));
  onStep('Initializing Git');
  try { runSilent('git init', { cwd: targetDir }); } catch {}
  onStep('Writing README');
  fs.writeFileSync(path.join(targetDir, 'README.md'), `# ${name}\n\nGenerated by **PIC-LI**\n\n\`\`\`bash\nnpm start\n\`\`\`\nOpen http://localhost:3000\n`);
}
module.exports = { generate };
