"use strict";

const fs = require("fs-extra");
const path = require("path");
const { runSilent } = require("../../core/runCommand");

async function generate({ name, template, targetDir, onStep }) {
  const parentDir = path.dirname(targetDir);

  const expoTemplates = {
    default: "blank",
    tabs: "tabs",
    "with-typescript": "blank-typescript",
  };
  const expoTpl = expoTemplates[template] || "blank";

  onStep("Scaffolding Expo project");
  runSilent(
    `npx --yes create-expo-app@latest "${name}" --template ${expoTpl}`,
    { cwd: parentDir }
  );

  if (!fs.existsSync(targetDir)) {
    throw new Error(`Expo scaffold did not create directory: ${targetDir}`);
  }

  onStep("Organising folder structure");

  if (template === "tabs") {
    scaffoldTabs(targetDir, name);
  } else if (template === "with-typescript") {
    scaffoldTypescript(targetDir, name);
  } else {
    scaffoldDefault(targetDir, name);
  }

  onStep("Initializing Git");
  try {
    runSilent("git init", { cwd: targetDir });
  } catch {}
  const gi = `node_modules/\n.expo/\ndist/\n.env\n.DS_Store\n*.jks\n*.p8\n*.p12\n*.key\n*.mobileprovision\n`;
  fs.writeFileSync(path.join(targetDir, ".gitignore"), gi);

  onStep("Writing README");
  fs.writeFileSync(path.join(targetDir, "README.md"), readme(name, template));
}

// ─── Template: Default ────────────────────────────────────────────────────────

function scaffoldDefault(targetDir, name) {
  const src = (...p) => path.join(targetDir, "src", ...p);

  fs.ensureDirSync(src("screens"));
  fs.ensureDirSync(src("components"));
  fs.ensureDirSync(src("hooks"));
  fs.ensureDirSync(src("services"));
  fs.ensureDirSync(src("utils"));

  fs.writeFileSync(src("screens", "HomeScreen.js"), defaultHomeScreen(name));
}

function defaultHomeScreen(name) {
  return `import { StyleSheet, Text, View } from 'react-native';

export default function HomeScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>${name}</Text>
      <Text style={styles.subtitle}>Generated by PIC-LI</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  title:     { fontSize: 28, fontWeight: '700', marginBottom: 8 },
  subtitle:  { fontSize: 16, color: '#666' },
});
`;
}

// ─── Template: Tabs ───────────────────────────────────────────────────────────

function scaffoldTabs(targetDir, name) {
  const src = (...p) => path.join(targetDir, "src", ...p);

  fs.ensureDirSync(src("navigation"));
  fs.ensureDirSync(src("screens"));
  fs.ensureDirSync(src("components"));
  fs.ensureDirSync(src("hooks"));

  fs.writeFileSync(src("screens", "HomeScreen.js"), tabHomeScreen(name));
  fs.writeFileSync(src("screens", "ProfileScreen.js"), tabProfileScreen());
  fs.writeFileSync(src("screens", "SettingsScreen.js"), tabSettingsScreen());
  fs.writeFileSync(src("navigation", "TabNavigator.js"), tabNavigator());
  fs.writeFileSync(src("navigation", "AppNavigator.js"), appNavigator());
}

function tabHomeScreen(name) {
  return `import { StyleSheet, Text, View } from 'react-native';

export default function HomeScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>${name}</Text>
      <Text style={styles.subtitle}>Home Tab</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  title:     { fontSize: 28, fontWeight: '700', marginBottom: 8 },
  subtitle:  { fontSize: 16, color: '#666' },
});
`;
}

function tabProfileScreen() {
  return `import { StyleSheet, Text, View } from 'react-native';

export default function ProfileScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Profile</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  title:     { fontSize: 28, fontWeight: '700' },
});
`;
}

function tabSettingsScreen() {
  return `import { StyleSheet, Text, View } from 'react-native';

export default function SettingsScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Settings</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  title:     { fontSize: 28, fontWeight: '700' },
});
`;
}

function tabNavigator() {
  return `import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import HomeScreen    from '../screens/HomeScreen';
import ProfileScreen from '../screens/ProfileScreen';
import SettingsScreen from '../screens/SettingsScreen';

const Tab = createBottomTabNavigator();

export default function TabNavigator() {
  return (
    <Tab.Navigator screenOptions={{ headerShown: false }}>
      <Tab.Screen name="Home"     component={HomeScreen} />
      <Tab.Screen name="Profile"  component={ProfileScreen} />
      <Tab.Screen name="Settings" component={SettingsScreen} />
    </Tab.Navigator>
  );
}
`;
}

function appNavigator() {
  return `import { NavigationContainer } from '@react-navigation/native';
import TabNavigator from './TabNavigator';

export default function AppNavigator() {
  return (
    <NavigationContainer>
      <TabNavigator />
    </NavigationContainer>
  );
}
`;
}

// ─── Template: TypeScript ─────────────────────────────────────────────────────

function scaffoldTypescript(targetDir, name) {
  const src = (...p) => path.join(targetDir, "src", ...p);

  fs.ensureDirSync(src("components"));
  fs.ensureDirSync(src("screens"));
  fs.ensureDirSync(src("hooks"));
  fs.ensureDirSync(src("services"));
  fs.ensureDirSync(src("types"));
  fs.ensureDirSync(src("utils"));

  fs.writeFileSync(src("screens", "HomeScreen.tsx"), tsHomeScreen(name));
  fs.writeFileSync(src("types", "navigation.ts"), tsNavigationTypes());
}

function tsHomeScreen(name) {
  return `import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../types/navigation';

type Props = NativeStackScreenProps<RootStackParamList, 'Home'>;

export default function HomeScreen({ navigation }: Props) {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>${name}</Text>
      <Text style={styles.subtitle}>Generated by PIC-LI</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  title:     { fontSize: 28, fontWeight: '700', marginBottom: 8 },
  subtitle:  { fontSize: 16, color: '#666' },
});
`;
}

function tsNavigationTypes() {
  return `export type RootStackParamList = {
  Home:    undefined;
  Profile: { userId: string };
  Settings: undefined;
};
`;
}

// ─── README ───────────────────────────────────────────────────────────────────

function readme(name, template) {
  const structures = {
    default: `\`\`\`
src/
  screens/      Screen components
  components/   Reusable UI components
  hooks/        Custom hooks
  services/     API / business logic
  utils/        Utilities
\`\`\``,

    tabs: `\`\`\`
src/
  navigation/
    AppNavigator.js
    TabNavigator.js
  screens/
    HomeScreen.js
    ProfileScreen.js
    SettingsScreen.js
  components/   Reusable UI components
  hooks/        Custom hooks
\`\`\``,

    "with-typescript": `\`\`\`
src/
  components/   Reusable UI components
  screens/      Screen components
  hooks/        Custom hooks
  services/     API / business logic
  types/
    navigation.ts
  utils/        Utilities
\`\`\``,
  };

  return `# ${name}

Generated by **PIC-LI** — Project Initializer Command

## Stack
- React Native + Expo (${template})

## Getting started

\`\`\`bash
npx expo start
\`\`\`

Press **a** for Android emulator, **i** for iOS simulator, **w** for web.

## Project structure

${structures[template] || structures.default}
`;
}

module.exports = { generate };
