"use strict";

const fs = require("fs-extra");
const path = require("path");
const { runSilent } = require("../../core/runCommand");

async function generate({ name, template, targetDir, onStep }) {
  const useTs = template.includes("typescript");
  const useTailwind = ["tailwind", "tailwind-shadcn"].includes(template);
  const ext = useTs ? "tsx" : "jsx";
  const viteTpl = useTs ? "react-ts" : "react";
  const parentDir = path.dirname(targetDir);

  onStep("Scaffolding with Vite");
  await runSilent(
    `npx --yes create-vite@latest "${name}" --template ${viteTpl}`,
    { cwd: parentDir }
  );

  onStep("Installing dependencies");
  await runSilent("npm install", { cwd: targetDir });

  if (useTailwind) {
    onStep("Installing Tailwind CSS v3");
    // Install Tailwind v3 explicitly — v4 has a different API
    await runSilent("npm install -D tailwindcss@3 postcss autoprefixer", {
      cwd: targetDir,
    });

    onStep("Writing Tailwind config (no npx init needed)");
    // Write tailwind.config.js manually — avoids the "npx tailwindcss init" failure
    fs.writeFileSync(
      path.join(targetDir, "tailwind.config.js"),
      `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: { extend: {} },
  plugins: [],
}
`
    );
    // Write postcss.config.js manually
    fs.writeFileSync(
      path.join(targetDir, "postcss.config.js"),
      `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`
    );
    // Overwrite index.css with Tailwind directives
    fs.writeFileSync(
      path.join(targetDir, "src", "index.css"),
      "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n"
    );
  }

  if (template === "tailwind-shadcn") {
    // create components.json
    fs.writeFileSync(
      path.join(targetDir, "components.json"),
      JSON.stringify(
        {
          style: "default",
          rsc: false,
          tsx: useTs,
          tailwind: {
            config: "tailwind.config.js",
            css: "src/index.css",
          },
          aliases: {
            components: "@/components",
            utils: "@/lib/utils",
          },
        },
        null,
        2
      )
    );

    // create lib/utils
    fs.ensureDirSync(path.join(targetDir, "src", "lib"));

    fs.writeFileSync(
      path.join(targetDir, "src", "lib", "utils.js"),
      `import { clsx } from "clsx";
  import { twMerge } from "tailwind-merge";
  
  export function cn(...inputs) {
    return twMerge(clsx(inputs));
  }
  `
    );

    await runSilent("npx shadcn-ui@latest add button", { cwd: targetDir });
  }

  onStep("Replacing App component");

  fs.writeFileSync(
    path.join(targetDir, "src", `App.${ext}`),
    appComponent(name, useTailwind, useTs)
  );
  if (!useTs) {
    fs.writeFileSync(
      path.join(targetDir, "jsconfig.json"),
      JSON.stringify(
        {
          compilerOptions: {
            baseUrl: ".",
            paths: {
              "@/*": ["src/*"],
            },
          },
        },
        null,
        2
      )
    );
  }
  onStep("Creating folder structure");
  fs.ensureDirSync(path.join(targetDir, "src", "components"));
  fs.ensureDirSync(path.join(targetDir, "src", "pages"));
  fs.ensureDirSync(path.join(targetDir, "src", "hooks"));
  fs.ensureDirSync(path.join(targetDir, "src", "assets"));

  onStep("Writing .env files");
  fs.writeFileSync(
    path.join(targetDir, ".env"),
    "VITE_APP_NAME=" + name + "\n"
  );
  fs.writeFileSync(path.join(targetDir, ".env.example"), "VITE_APP_NAME=\n");

  onStep("Initializing Git");
  try {
    runSilent("git init", { cwd: targetDir });
  } catch {}
  fs.writeFileSync(path.join(targetDir, ".gitignore"), gitignore());

  onStep("Writing README");
  fs.writeFileSync(path.join(targetDir, "README.md"), readme(name, template));
}

function appComponent(name, tailwind, ts) {
  if (tailwind) {
    return `${ts ? "import React from 'react';\n\n" : ""}function App() {
  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-gray-900 mb-2">${name}</h1>
        <p className="text-gray-500">Generated by PIC-LI &mdash; React + Vite + Tailwind</p>
      </div>
    </div>
  );
}

export default App;
`;
  }
  return `${ts ? "import React from 'react';\n\n" : ""}function App() {
  return (
    <div>
      <h1>${name}</h1>
      <p>Generated by PIC-LI</p>
    </div>
  );
}

export default App;
`;
}

function gitignore() {
  return `node_modules/\ndist/\n.env\n.env.local\n.DS_Store\ncoverage/\n`;
}

function readme(name, template) {
  return `# ${name}

Generated by **PIC-LI** — Project Initializer Command

## Stack
- React${template.includes("typescript") ? " + TypeScript" : ""}
- Vite${template.includes("tailwind") ? " + Tailwind CSS v3" : ""}${
    template === "tailwind-shadcn" ? " + shadcn/ui" : ""
  }

## Getting started

\`\`\`bash
npm run dev
\`\`\`

Open http://localhost:5173

## Commands

| Command | Description |
|---------|-------------|
| \`npm run dev\` | Start dev server |
| \`npm run build\` | Build for production |
| \`npm run preview\` | Preview production build |
`;
}

module.exports = { generate };
